### ISSUE TITLE
Issue with sagepay_failure url

### ISSUE THREAD

**Issue by bloomonkey2020** [edbeeny/community_store_sagepay#1]
I have been getting an intermittent failure when customers are making payments using sage pay on my clients website.

The error  code in sage pay is 3085 which is a failure url error. I have pasted  and attached the section of the error report from sage pay where it states the sagepay_failure url. 

Sage Pay help desk mentioned that the error occurred because there is a 'space" in the url directly after 'sagepay_failure'  and before 'A'  - see the below urls which came from the error report, notice the sagepay_success has no space:

`
successurl=https://www.atlanticlights.co.uk/checkout/sagepay_successA failureurl=https://www.atlanticlights.co.uk/checkout/sagepay_failure A 
`

I have searched through all the files and cannot for the life of me find where this space is creeping in, and I do not know how to contact mr Edbeeny.

<img width="453" alt="Screenshot 2020-05-18 at 17 14 44" src="https://user-images.githubusercontent.com/61829717/82240244-fb7de300-9931-11ea-8335-3ca40f8a7b56.png">

**Comment by edbeeny** [comment]
Hi, Not sure where the A is coming from.
Have you tried to use server authentication, I have found this to be less troublesome with sage pay?

Thanks
Ed

**Comment by bloomonkey2020** [comment]
Hi Ed

Thanks for replying so quickly, I tried to do the server option instead of Form, but the checkout just goes round in a loop likes its constantly trying to load and redirect and wont connect through to sage.

**Comment by bloomonkey2020** [comment]
Hi Ed,

I have been looking at the server side today. It brings the orders into the dashboard for me to view, but when I click on manage I get the attached error `Call to a member function gettransTotal() on null`
<img width="1379" alt="Screenshot 2020-05-19 at 10 47 16" src="https://user-images.githubusercontent.com/61829717/82311996-5ceb9380-99be-11ea-9172-574680f54b80.png">

**Comment by edbeeny** [comment]
Have you got the latest version installed 0.92?
I thought this issue was fixed.

**Comment by bloomonkey2020** [comment]
Every download I find seems to say 0.90, but the controller says 0.92? I went through all the files today to see if I had the latest updates, but it is entirely possible that I missed something. 

Also the checkout redirect to sage still just loops and doesn't redirect. The url is `/checkout/external#`

**Comment by bloomonkey2020** [comment]
Hi Ed,

After spending a few hours playing around, I do have all of the up to date files and I still get the same errors. It cant find the transaction total attribute.  

Sorry to be a pest.

**Comment by bloomonkey2020** [comment]
success.

Concerning the original issue with the failureurl and the 3085 error, it looks like it was because there are underscores in the success and failure url's rather than dashes. Once I swapped all them out we couldn't replicate the error.

**Comment by edbeeny** [comment]
Okay, well done thanks for finding that error, I will add that fix. 
I will have a look at the server issue, not sure why you have experienced that.
